# Basic Site Settings
locale: "en-US"  # specifies the language and region of your website
title: "Rohith Reddy K"  # Title of the site
title_separator: "-"     
name: "Rohith Reddy K"  # some themes pick up name instead of author's name
description: "Your personal website"  # Basic description
url: "https://Rohith2102.github.io"   
baseurl: ""  # Leave this empty since your site is at the root if u are not at root rohith.github.io/portfolio then you fill it with /porfolio
repository: "Rohith2102/Rohith2102.github.io"
theme: jekyll-theme-minimal  # the theme you wanna use

# Site Author
author:
  avatar: "my-profile-img.png"  # profile pic
  name: "Rohith Reddy K"   # name
  bio: "Software Engineer" # short Bio
  location: "California, USA"  # Location
  email: "krohithreddyk2@gmail.com" # Email
  github: "Rohith2102"   # Username only
  linkedin: "rohith-k"    # username only
  university: "UC Riverside"


# By default Jekyll excludes directories/files(In build process) that start with an underscore
# Include the _pages directory
include:
  - _pages



# Collections
collections:
  publications:
    output: true
    permalink: /publications/:title/
  talks:
    output: true
    permalink: /talks/:title/

# Defaults
defaults:
  # Pages in _pages directory
  - scope:
      path: "_pages"
      type: "page"
    values:
      layout: default
  # Publications collection
  - scope:
      path: ""
      type: "publications"
    values:
      layout: default
      author_profile: true
  # Talks collection
  - scope:
      path: ""
      type: "talks"
    values:
      layout: default
      author_profile: true

# Markdown Processing
markdown: kramdown


# Permalinks
permalink: /:title/

