# Basic Site Settings
locale: "en-US"
title: "Rohith Reddy K"
title_separator: "-"
name: "Rohith Reddy K"
description: "Your personal website"
url: "https://Rohith2102.github.io"
baseurl: ""  # Leave this empty since your site is at the root
repository: "Rohith2102/Rohith2102.github.io"

# Site Author
author:
  avatar: "profile.png"
  name: "Rohith Reddy K"
  bio: "Software Engineer"
  location: "California, USA"
  email: "krohithreddyk2@gmail.com"
  github: "Rohith2102"
  linkedin: "rohith-k"
  university: "UC Riverside"

sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - _sass



# Include the _pages directory
include:
  - _pages
  - _sass


# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:title/
  talks:
    output: true
    permalink: /talks/:title/

# Defaults
defaults:
  # Pages in _pages directory
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: default
      permalink: "/:title/"
  # Publications collection
  - scope:
      path: ""
      type: "publications"
    values:
      layout: default
      author_profile: true
  # Talks collection
  - scope:
      path: ""
      type: "talks"
    values:
      layout: default
      author_profile: true

# Markdown Processing
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /:title/

# Plugins Configuration
jekyll-feed:
  path: atom.xml

# SEO and Analytics (Optional)
# Uncomment and set your Google Analytics ID if you have one
# analytics:
#   provider: "google"
#   google:
#     tracking_id: "UA-XXXXXXXXX-X"
